# Generated by Django 3.2.8 on 2021-12-08 09:05

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_change',
            fields=[
                ('header_id', models.AutoField(primary_key=True, serialize=False)),
                ('header_title', models.CharField(max_length=50)),
                ('header_image', models.ImageField(null=True, upload_to='images/')),
                ('header_slogan', models.CharField(max_length=100)),
                ('header_border_background_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('header_background_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('header_slogan_background_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('header_slogan_top_background_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('header_slogan_font_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('header_title_font_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('navigation_button_text_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('navigation_bar_background_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('navigation_button_background_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('navigation_bar_sub_buttons_background_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('navigation_bar_sub_button_font_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('navigation_drop_down_background_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('section_button_background_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('section_button_font_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('section_background_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('section_header_font_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('section_text_font_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('section_border_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.TextField()),
                ('post_preview_text', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('header_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=100)),
                ('topic_image', models.ImageField(null=True, upload_to='images/')),
                ('topic_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='home_page_section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_title', models.CharField(max_length=300)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('section_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.blog_post')),
            ],
        ),
        migrations.AddField(
            model_name='blog_post',
            name='topic',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='blog.topic'),
        ),
    ]
