# Generated by Django 2.0.13 on 2021-09-15 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_change',
            fields=[
                ('header_id', models.AutoField(primary_key=True, serialize=False)),
                ('header_title', models.CharField(max_length=50)),
                ('header_image', models.ImageField(null=True, upload_to='images/')),
                ('header_slogan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=100)),
                ('post_preview_text', models.CharField(max_length=300)),
                ('post_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='home_page_section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_title', models.CharField(max_length=300)),
                ('header_image', models.ImageField(null=True, upload_to='images/')),
                ('section_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.blog_post')),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('header_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=100)),
                ('topic_image', models.ImageField(null=True, upload_to='images/')),
                ('topic_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='blog_post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.topic'),
        ),
    ]
