# Generated by Django 2.0.13 on 2021-09-18 12:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_change',
            name='navigation_bar_backgrond_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='blog_change',
            name='navigation_button_text_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
