# Generated by Django 2.0.13 on 2021-09-18 13:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210918_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_change',
            name='navigation_text_background_color',
        ),
        migrations.AddField(
            model_name='blog_change',
            name='navigation_bar_sub_button_font_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='blog_change',
            name='navigation_bar_sub_buttons_background_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
