# Generated by Django 2.0.13 on 2021-09-26 06:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
