# Generated by Django 2.0.13 on 2021-10-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blog_post_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page_section',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
