# Generated by Django 2.0.13 on 2021-10-17 08:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211001_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
