# Generated by Django 2.0.13 on 2021-10-17 08:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211017_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
