# Generated by Django 3.2.8 on 2021-11-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211017_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='post_title',
            field=models.TextField(),
        ),
    ]
