# Generated by Django 3.2.8 on 2021-11-05 05:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blog_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_change',
            name='header_slogan_bottom_background_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='blog_change',
            name='header_slogan_top_background_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
