# Generated by Django 3.2.8 on 2021-11-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20211105_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_change',
            name='header_slogan_bottom_background_color',
        ),
    ]
