# Generated by Django 3.2.8 on 2021-11-08 08:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_blog_change_header_slogan_bottom_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_change',
            name='navigation_drop_down_background_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
