# Generated by Django 3.2.8 on 2021-11-25 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_change_navigation_drop_down_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.topic'),
        ),
    ]
