# Generated by Django 3.2.8 on 2021-11-25 01:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blog_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_change',
            name='section_border_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
