# Generated by Django 3.2.8 on 2021-12-06 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_blog_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='topic',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='blog.topic'),
        ),
    ]
